package com.example.VeristasId.Model;

import org.junit.jupiter.api.Test;
import java.lang.reflect.Field;
import jakarta.persistence.*;
import static org.junit.jupiter.api.Assertions.*;

class EntityModelTest {

    // ── MedicalRecord ──────────────────────────────────────────────────────

    @Test
    void medicalRecord_setAndGet_allFields() {
        MedicalRecord r = new MedicalRecord();
        r.setAbhaId("99-9999-9999-9999");
        r.setPatientName("John Doe");
        r.setBloodGroup("O-Negative");
        r.setAllergies("Penicillin");
        r.setStatus("PENDING_BIOMETRIC_MERGE");

        assertEquals("99-9999-9999-9999",       r.getAbhaId());
        assertEquals("John Doe",                 r.getPatientName());
        assertEquals("O-Negative",               r.getBloodGroup());
        assertEquals("PENDING_BIOMETRIC_MERGE",  r.getStatus());
    }

    @Test
    void medicalRecord_allArgsConstructor_works() {
        // Verifies @AllArgsConstructor generated the right constructor
        MedicalRecord r = new MedicalRecord(
            1L, "did:veristas:patient:abc", "99-9999",
            "did:veristas:hospital:xyz", "ES-001",
            "Jane", "AB+", "None", "ACTIVE",
            "Fever", "BP:120/80", "Paracetamol", null
        );
        assertEquals("Jane",   r.getPatientName());
        assertEquals("ES-001", r.getEsid());
    }

    @Test
    void medicalRecord_twoEqualObjects_areEqual() {
        // Verifies @Data generates equals() correctly
        MedicalRecord r1 = new MedicalRecord();
        r1.setAbhaId("99-9999");
        r1.setPatientName("John");

        MedicalRecord r2 = new MedicalRecord();
        r2.setAbhaId("99-9999");
        r2.setPatientName("John");

        assertEquals(r1, r2);       // @Data generates equals()
        assertEquals(r1.hashCode(), r2.hashCode()); // @Data generates hashCode()
    }

    // ── Consent ────────────────────────────────────────────────────────────

    @Test
    void consent_activeFlag_defaultFalse() {
        Consent c = new Consent();
        assertFalse(c.isActive()); // boolean primitive defaults to false
    }

    @Test
    void consent_fields_storeCorrectly() {
        Consent c = new Consent(
            null,
            "did:veristas:patient:abc",
            "did:veristas:hospital:xyz",
            "emergency_access",
            true,
            "signature_here"
        );
        assertEquals("emergency_access", c.getPurpose());
        assertTrue(c.isActive());
        assertEquals("did:veristas:patient:abc", c.getPatientDid());
    }

    // ── EmergencySessionEntity ─────────────────────────────────────────────

    @Test
    void emergencySession_stringPrimaryKey_notAutoGenerated() throws Exception {
        // Verify @Id is on a String field (not Long with @GeneratedValue)
        Field esidField = EmergencySessionEntity.class.getDeclaredField("esid");
        assertNotNull(esidField.getAnnotation(Id.class));
        assertNull(esidField.getAnnotation(GeneratedValue.class)); // ← no auto-increment!
    }

    @Test
    void emergencySession_stageLifecycle() {
        EmergencySessionEntity session =
            new EmergencySessionEntity("ES-001", "PAT-001", "dispatched", System.currentTimeMillis());

        assertEquals("dispatched", session.getStage());

        session.setStage("arrived");    // simulate stage progression
        assertEquals("arrived", session.getStage());

        session.setStage("completed");
        assertEquals("completed", session.getStage());
    }

    // ── AuditBlockEntity ───────────────────────────────────────────────────

    @Test
    void auditBlock_hashColumn_isLength64() throws Exception {
        Field hashField = AuditBlockEntity.class.getDeclaredField("hash");
        Column col = hashField.getAnnotation(Column.class);
        assertNotNull(col, "hash field must have @Column annotation");
        assertEquals(64, col.length(), "SHA-256 hex = exactly 64 chars");
    }

    @Test
    void auditBlock_setAndGet_allFields() {
        AuditBlockEntity e = new AuditBlockEntity();
        e.setBlockIndex(1);
        e.setAccessorId("Paramedic_JWT");
        e.setTargetAbhaId("99-9999-9999-9999");
        e.setAction("READ");
        e.setAccessGranted(true);
        e.setPreviousHash("0000000000000000");
        e.setHash("a".repeat(64)); // 64-char fake hash

        assertEquals(1,                    e.getBlockIndex());
        assertTrue(e.isAccessGranted());
        assertEquals(64, e.getHash().length());
    }

    // ── VCEntity ───────────────────────────────────────────────────────────

    @Test
    void vcEntity_proofColumn_isTextType() throws Exception {
        Field proofField = VCEntity.class.getDeclaredField("proof");
        Column col = proofField.getAnnotation(Column.class);
        assertEquals("TEXT", col.columnDefinition(),
            "proof must be TEXT not VARCHAR(255) — JWTs can be very long");
    }

    @Test
    void vcEntity_revoked_defaultsFalse() {
        VCEntity vc = new VCEntity();
        assertFalse(vc.isRevoked(),
            "A new credential must not be revoked by default");
    }

    @Test
    void vcEntity_subjectDid_notNullable() throws Exception {
        Field field = VCEntity.class.getDeclaredField("subjectDid");
        Column col = field.getAnnotation(Column.class);
        assertFalse(col.nullable(), "subjectDid must be NOT NULL");
    }
}
